config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  has_many :comments, dependent: :destroy
  #belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 1 }

end

app/models/comment.rb
class Comment < ApplicationRecord
include Visible

  #belongs_to :article # это выражение делает каждый комментарий принадлежащим статье, к которой написан
  #belongs_to :user
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']
  
  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end
  
  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

#has_many :articles
#has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all #извлекаем все статьи из БД
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article=Article.new
  end

  def create
    @article=Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article=Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path, status: :see_other
  end

  private
   def article_params
     params.require(:article).permit(:title, :body, :status)
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
    end

    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article), status: :see_other
    end
  
    private
      def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
      end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1"> <%= form.label :title %></span>
    <input type="text" class="form-control" placeholder="" aria-label=<%= form.text_field :title %> 
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1"> <%= form.label "Text" %></span>
    <textarea class="form-control" placeholder="" aria-label=<%= form.text_area :body%> 
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], {}, {class: "form-select", } %>
  </div>

  <br>
  
  <div>
    <%= form.submit "Create Article", class: "btn btn-primary"%>
  </div>
<% end %>

  

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h3>Articles</h3>

Our blog has <%= Article.public_count %> articles and counting!

  <% @articles.each do |article| %>
    <div class="card" style="width: 50rem;">
      <div class="card-body">
        <h5 class="card-title"><%= article.title %></h5>
        <p class="card-text"><%= article.body %></p>
        <a href=<%=article_path(article.id)%>  class="btn btn-primary"><%= link_to "Read the comments", article_path(article.id)%></a>
      </div>
    </div>
  <% end %>

<td><%= link_to "New Article", new_article_path , class: "btn btn-primary" %></td>

app/views/articles/new.html.erb
<h3>New Article</h3>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>

<p><%= @article.body %></p>
<% if @article.created_at != @article.updated_at %>
  <p> Updated at: <%= @article.updated_at %></p>
<% else %>
  <p> Created at: <%= @article.created_at %></p>
<% end %>


  <%= link_to "Edit", edit_article_path(@article), class: "btn btn-success" %>
  <%= link_to "Destroy", article_path(@article), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"  
  }, class: "btn btn-danger"%>

  <br>
  </br>

<h4>Comments</h4>
<%= render @article.comments %>

<h4>Add a comment:</h4>
<%= render "comments/form" %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
     turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    }, class: "btn btn-danger" %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>

    <div class="input-group mb-3">
      <span class="input-group-text" id="basic-addon1"> <%= form.label :commenter %></span>
      <input type="text" class="form-control" placeholder="" aria-label=<%= form.text_field :commenter %>
    </div>

    <div class="input-group mb-3">
      <span class="input-group-text" id="basic-addon1"> <%= form.label "Text" %></span>
      <textarea class="form-control" placeholder="" aria-label=<%= form.text_area :body%> 
    </div>

    <div>
      <%= form.label :status %><br>
      <%= form.select :status, ['public', 'private', 'archived'], {}, {class: "form-select", }%>
    </div>
    <br>
    <div>
      <%= form.submit "Create comment", class: "btn btn-success" %>
    </div>
  <% end %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render "special_layouts/header" %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>

    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link"  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
      <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
    <% end %>
    </p>
  </body>
</html>

app/views/special_layouts/_header.html.erb
<nav class="navbar navbar-light navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href= <%= root_path %>>Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">

      <li class="nav-item">
        <a class="nav-link" aria-current="page" href= <%= articles_path %>>Show the articles</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" aria-current="page" href= <%= new_article_path%>>Create new article</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" aria-current="page" href= <%=edit_user_registration_path%>>Edit profile</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" aria-current="page" href= <%=new_user_registration_path%>>Sign up</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" aria-current="page" href= <%=new_user_session_path%>>Login</a>
      </li>
        
      </ul>
    </div>
  </div>
</nav>

<p>WELCOME TO MY AWESOME BLOG</p>